In [113]:
import pandas as pd;
import numpy as np;
from sklearn.model_selection import train_test_split;
from sklearn.impute import SimpleImputer;
from sklearn.preprocessing import OneHotEncoder;

In [ ]:
# Importing the dataframe
df = pd.read_csv('../datasets/train.csv');

In [115]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [116]:
df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'],inplace=True, axis = 1)

In [117]:
df.head(5)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [118]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df['Survived'], test_size=0.3, random_state=0)

In [119]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [120]:
# Applying Imputation on the "Age" and "Embarked" column since they contain missing values
si_age = SimpleImputer(strategy='mean');
si_transform = SimpleImputer(strategy='most_frequent');

X_train_age = si_age.fit_transform(X_train[["Age"]])
X_train_embarked = si_transform.fit_transform(X_train[["Embarked"]])

X_test_age = si_age.transform(X_test[["Age"]])
X_test_embarked = si_transform.transform(X_test[["Embarked"]])

In [121]:
# Performing One Hot Encoder on the "Embarked" and "Sex" column
ohe_embarked = OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore');
X_train_embarked = ohe_embarked.fit_transform(X_train_embarked);
X_test_embarked = ohe_embarked.transform(X_test_embarked);

ohe_gender = OneHotEncoder(drop='first', sparse_output=False);
X_train_gender = ohe_gender.fit_transform(X_train[['Sex']]);
X_test_gender = ohe_gender.transform(X_test[['Sex']]);

In [127]:
df1 = pd.concat([pd.DataFrame(X_train_age),
     pd.DataFrame(X_train_embarked),
     pd.DataFrame(X_train_gender)],
    axis=1
).reset_index(drop=True)

X_train_remaining = X_train.drop(['Sex', 'Age', 'Embarked'], axis = 1).reset_index(drop=True)
X_train_final = pd.concat([X_train_remaining, df1], axis = 1)
X_train_final

     Pclass  SibSp  Parch     Fare          0    0    1    0
0         1      0      0  26.5500  51.000000  0.0  1.0  1.0
1         1      1      0  76.7292  49.000000  0.0  0.0  0.0
2         3      5      2  46.9000   1.000000  0.0  1.0  1.0
3         1      0      1  77.2875  54.000000  0.0  1.0  1.0
4         3      1      0  14.4583  29.915339  0.0  0.0  0.0
..      ...    ...    ...      ...        ...  ...  ...  ...
618       1      1      1  83.1583  39.000000  0.0  0.0  0.0
619       3      1      0   7.8542  19.000000  0.0  1.0  0.0
620       3      0      0   7.7333  29.915339  1.0  0.0  1.0
621       3      1      0  17.4000  36.000000  0.0  1.0  0.0
622       2      1      1  39.0000  60.000000  0.0  1.0  1.0

[623 rows x 8 columns]

In [128]:
X_train

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
857       1    male  51.0      0      0  26.5500        S
52        1  female  49.0      1      0  76.7292        C
386       3    male   1.0      5      2  46.9000        S
124       1    male  54.0      0      1  77.2875        S
578       3  female   NaN      1      0  14.4583        C
..      ...     ...   ...    ...    ...      ...      ...
835       1  female  39.0      1      1  83.1583        C
192       3  female  19.0      1      0   7.8542        S
629       3    male   NaN      0      0   7.7333        Q
559       3  female  36.0      1      0  17.4000        S
684       2    male  60.0      1      1  39.0000        S

[623 rows x 7 columns]