In [10]:
# How to check if pandas is intalled on your system or not
# !pip show pandas
# !pip show numpy

In [ ]:
# Import Pandas and NumPy, then build a DataFrame from a 2D NumPy array
import pandas as pd
import numpy as np

# Step1: Creating a data frame in pandas from a 2darray
matrix = np.array([[1,2,3],[4,5,6]])

df = pd.DataFrame(matrix)
df

   0  1  2
0  1  2  3
1  4  5  6

In [ ]:
# Build DataFrames from dictionaries and rename columns when needed

dict_students = {"Ayush": ["Himanshu",4,6], "Himanshu": [3,5,7]}
df_students = pd.DataFrame(dict_students)
print(df_students)

dict_passengers = {"Name" :["A", "B", "C"],
                   "Age": [12,13,14],
                   "Sex": ["M", "F", "M"]};

# df = pd.DataFrame(dict_passengers) -- In this case the column heading will be same as the keys of the dictionary
# But in case we want different column name at the time of creation of the data frame 
df_passengers = pd.DataFrame(dict_passengers.values(), columns = ["Name_M", "Age_M", "Sex_M"])
df_passengers

      Ayush  Himanshu
0  Himanshu         3
1         4         5
2         6         7

  Name_M Age_M Sex_M
0      A     B     C
1     12    13    14
2      M     F     M

In [ ]:
# Compare NumPy array conversion from dictionary values
dict_passengers = {"Name" :["A", "B", "C"],
                   "Age": [12,13,14],
                   "Sex": ["M", "F", "M"]};

array1 = np.array(list(dict_passengers.values()))
array2 = np.array(dict_passengers.values())

print(array1.dtype)
print(array2.dtype)

<U21
object

In [ ]:
# Create a small DataFrame and use it to show that a column is a Series
import pandas as pd

df = pd.DataFrame({
    "Name" :["A", "B"],
    "Age": [28, 40]
})

# print(df["Age"]) -> Series
# print(df["Age"].dtype) -> Series ka Datatype

<class 'pandas.core.series.Series'>

In [ ]:
# Access the Name column values from the dictionary
dict_passengers["Name"]

['A', 'B', 'C']

In [ ]:
# Work with a Series, update a DataFrame column, and inspect summary info
series = pd.Series(["A", "B", "C"])
type(series)

# This is how we can reupdate a series or a column of a data frame
df_passengers["Age_M"] = pd.Series([11,12,13])
# How to calucalte the maximum value of Age
df_passengers["Age_M"].max()

df_passengers["Age_M"].dtype
df_passengers["Name_M"].dtype

df_passengers.describe()

df_passengers.select_dtypes(include = np.int64)

   Age_M
0     11
1     12
2     13

In [ ]:
# Read, inspect, and transform Titanic data, then write it back out

# df = pd.read_csv("")
# method to read the titanic.csv file
df = pd.read_csv("./titanic.csv")
# there are other method similair to read csv like read_excel, read_clipbaord that we can explore

# In case suppose you want to read only tope 12 rows 
df.head(n = 12)
df.tail(n = 12)


# This will add prefix = Himanshu_ and it will add in column heading
df.add_prefix(prefix = "Himanshu_", axis = 1).head(12)

# df.count() -> This will give non-NA cells for each column or row, for column set axis = 0 else row wise axis = 1



# Getting count of the data element which are not-nan
print(df["Age"].count())

# Getting first 5 rows of the data frame
print(df["Age"].head(5))
# Implementing iterator over the dataframe - series
df["Age"] = df["Age"].map(lambda x: x + 1)
print(df["Age"].head(5))

# Similiar to read_csv we also have to_csv, to_excel ...
df.to_csv("titanic_2.csv")

714
0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64
0    23.0
1    39.0
2    27.0
3    36.0
4    36.0
Name: Age, dtype: float64

In [ ]:
# Reload the transformed CSV and inspect its dtypes
import pandas as pd;
df = pd.read_csv("./titanic_2.csv");

# Its answer is 13, it means there are 13 columns
df.dtypes

# There is one thing called df.describe and other is df.info()
# df.describe(percentiles = [0.25, 0.50, 0.70, 0.80], include = [np.int64])
# df.describe(percentiles = [0.25, 0.50, 0.70, 0.80], include = [np.float64])
# df.describe(percentiles = [0.25, 0.50, 0.70, 0.80], include = [np.object_])

Unnamed: 0       int64
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
# Show the full DataFrame structure with null counts and dtypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   891 non-null    int64
 1   PassengerId  891 non-null    int64
 2   Survived     891 non-null    int64
 3   Pclass       891 non-null    int64
 4   Name         891 non-null    object
 5   Sex          891 non-null    object
 6   Age          714 non-null    float64
 7   SibSp        891 non-null    int64
 8   Parch        891 non-null    int64
 9   Ticket       891 non-null    object
 10  Fare         891 non-null    float64
 11  Cabin        204 non-null    object
 12  Embarked     889 non-null    object
dtypes: float64(2), int64(6), object(5)
memory usage: 90.6+ KB

In [ ]:
# Select subsets of the Titanic DataFrame with get and column indexing
df_titanic = pd.DataFrame(pd.read_csv("./titanic.csv"))

# Option1: df.get(key = object) - > This does not thorw error if coumn deos not exist
df_titanic.get(key = ["Age", "Sex"])
df_titanic[["Age", "Sex"]]
# Both of the above provide same answer but there is a catch here, consider if the column does not exist
# df_titanic.get(key = ["Age", "Sex", "Sexy"]) -> this return none
# df_titanic[["Age", "Sex", "Sexy"]] -> this return error

# This is not returning any data becuase here when we use tuple as key(It expect object, tuple is also a object by default), but this will work for table having multi column index
# df_titanic.get(key = ("Age", "Sex"))

Hi there

In [ ]:
# Count passengers older than 35 by filtering the DataFrame first
df_titanic[df_titanic["Age"] > 35]["Name"].count()

np.int64(217)

In [ ]:
# Use isin, isna, loc, and iloc to filter rows and inspect slices
(row, col) = df_titanic[df_titanic["Pclass"].isin(values = [2,3])].shape
row


df_titanic[df_titanic["Age"].isna() == False]

df_titanic[df_titanic["Age"] >= 35]["Name"]

df_titanic.loc[df_titanic["Age"] > 35, "Name"]


df_titanic.iloc[10:25, 3:5]

                                                 Name     Sex
10                     Sandstrom, Miss Marguerite Rut  female
11                            Bonnell, Miss Elizabeth  female
12                     Saundercock, Mr. William Henry    male
13                        Andersson, Mr. Anders Johan    male
14                Vestrom, Miss Hulda Amanda Adolfina  female
15                   Hewlett, Mrs. (Mary D Kingcome)   female
16                                Rice, Master Eugene    male
17                       Williams, Mr. Charles Eugene    male
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female
19                            Masselmani, Mrs. Fatima  female
20                               Fynney, Mr. Joseph J    male
21                              Beesley, Mr. Lawrence    male
22                         McGowan, Miss Anna "Annie"  female
23                       Sloper, Mr. William Thompson    male
24                       Palsson, Miss Torborg Danira  female

In [ ]:
# Check whether matplotlib is installed for later visualizations
!pip show matplotlib

Name: matplotlib
Version: 3.10.6
Summary: Python plotting package
Home-page: https://matplotlib.org
Author: John D. Hunter, Michael Droettboom
Author-email: Unknown <matplotlib-users@python.org>
License: License agreement for matplotlib versions 1.3.0 and later
 =========================================================

 1. This LICENSE AGREEMENT is between the Matplotlib Development Team
 ("MDT"), and the Individual or Organization ("Licensee") accessing and
 otherwise using matplotlib software in source or binary form and its
 associated documentation.

 2. Subject to the terms and conditions of this License Agreement, MDT
 hereby grants Licensee a nonexclusive, royalty-free, world-wide license
 to reproduce, analyze, test, perform and/or display publicly, prepare
 derivative works, distribute, and otherwise use matplotlib
 alone or in any derivative version, provided, however, that MDT's
 License Agreement and MDT's notice of copyright, i.e., "Copyright (c)
 2012- Matplotlib Development Team; All Rights Reserved" are retained in
 matplotlib  alone or in any derivative version prepared by
 Licensee.

 3. In the event Licensee prepares a derivative work that is based on or
 incorporates matplotlib or any part thereof, and wants to
 make the derivative work available to others as provided herein, then
 Licensee hereby agrees to include in any such work a brief summary of
 the changes made to matplotlib .

 4. MDT is making matplotlib available to Licensee on an "AS
 IS" basis.  MDT MAKES NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR
 IMPLIED.  BY WAY OF EXAMPLE, BUT NOT LIMITATION, MDT MAKES NO AND
 DISCLAIMS ANY REPRESENTATION OR WARRANTY OF MERCHANTABILITY OR FITNESS
 FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF MATPLOTLIB
 WILL NOT INFRINGE ANY THIRD PARTY RIGHTS.

 5. MDT SHALL NOT BE LIABLE TO LICENSEE OR ANY OTHER USERS OF MATPLOTLIB
  FOR ANY INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES OR
 LOSS AS A RESULT OF MODIFYING, DISTRIBUTING, OR OTHERWISE USING
 MATPLOTLIB , OR ANY DERIVATIVE THEREOF, EVEN IF ADVISED OF
 THE POSSIBILITY THEREOF.

 6. This License Agreement will automatically terminate upon a material
 breach of its terms and conditions.

 7. Nothing in this License Agreement shall be deemed to create any
 relationship of agency, partnership, or joint venture between MDT and
 Licensee.  This License Agreement does not grant permission to use MDT
 trademarks or trade name in a trademark sense to endorse or promote
 products or services of Licensee, or any third party.

 8. By copying, installing or otherwise using matplotlib ,
 Licensee agrees to be bound by the terms and conditions of this License
 Agreement.

 License agreement for matplotlib versions prior to 1.3.0
 ========================================================

 1. This LICENSE AGREEMENT is between John D. Hunter ("JDH"), and the
 Individual or Organization ("Licensee") accessing and otherwise using
 matplotlib software in source or binary form and its associated
 documentation.

 2. Subject to the terms and conditions of this License Agreement, JDH
 hereby grants Licensee a nonexclusive, royalty-free, world-wide license
 to reproduce, analyze, test, perform and/or display publicly, prepare
 derivative works, distribute, and otherwise use matplotlib
 alone or in any derivative version, provided, however, that JDH's
 License Agreement and JDH's notice of copyright, i.e., "Copyright (c)
 2002-2011 John D. Hunter; All Rights Reserved" are retained in
 matplotlib  alone or in any derivative version prepared by
 Licensee.

 3. In the event Licensee prepares a derivative work that is based on or
 incorporates matplotlib  or any part thereof, and wants to
 make the derivative work available to others as provided herein, then
 Licensee hereby agrees to include in any such work a brief summary of
 the changes made to matplotlib.

 4. JDH is making matplotlib  available to Licensee on an "AS
 IS" basis.  JDH MAKES NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR
 IMPLIED.  BY WAY OF EXAMPLE, BUT NOT LIMITATION, JDH MAKES NO AND
 DISCLAIMS ANY REPRESENTATION OR WARRANTY OF MERCHANTABILITY OR FITNESS
 FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF MATPLOTLIB
 WILL NOT INFRINGE ANY THIRD PARTY RIGHTS.

 5. JDH SHALL NOT BE LIABLE TO LICENSEE OR ANY OTHER USERS OF MATPLOTLIB
  FOR ANY INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES OR
 LOSS AS A RESULT OF MODIFYING, DISTRIBUTING, OR OTHERWISE USING
 MATPLOTLIB , OR ANY DERIVATIVE THEREOF, EVEN IF ADVISED OF
 THE POSSIBILITY THEREOF.

 6. This License Agreement will automatically terminate upon a material
 breach of its terms and conditions.

 7. Nothing in this License Agreement shall be deemed to create any
 relationship of agency, partnership, or joint venture between JDH and
 Licensee.  This License Agreement does not grant permission to use JDH
 trademarks or trade name in a trademark sense to endorse or promote
 products or services of Licensee, or any third party.

 8. By copying, installing or otherwise using matplotlib,
 Licensee agrees to be bound by the terms and conditions of this License
 Agreement.
Location: /opt/anaconda3/lib/python3.13/site-packages
Requires: contourpy, cycler, fonttools, kiwisolver, numpy, packaging, pillow, pyparsing, python-dateutil
Required-by: ipympl, seaborn